# Generated by Django 4.0.5 on 2022-08-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileConverter', '0002_musicfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicfile',
            name='name',
        ),
    ]
